cl: Fix Windows build.
Fixes two trivial issues:

- on Windows large integers like 0xff000001 are not `int` objects, but
  rather `long` objects, so accept both types.

- and the error message caused exception

   TypeError: cannot concatenate 'str' and 'long' objects