cmake: Require egl 11.0.
mesa 11.0 is needed for EGLDeviceEXT symbol.

egl_ext_device_query.c: In function ‘main’:
egl_ext_device_query.c:33:2: error: unknown type name ‘EGLDeviceEXT’
  EGLDeviceEXT device = EGL_NO_DEVICE_EXT;
  ^

Signed-off-by: Vinson Lee <vlee@freedesktop.org>