tox: Remove testing of end-of-life Python 3.3
Python 3.3 reached end-of-life in September 2017 [0].

Continuous integration testing has identified a number of dependencies are
now failing on python 3.3, such as:

  Collecting wheel
  wheel requires Python '>=2.7, !=3.0.*, !=3.1.*, !=3.2.*, !=3.3.*' but the running Python is 3.3.6
  ...
  OSError: Command /home/travis/build/E...generator/bin/python - setuptools pip wheel failed with error code 1

[0] https://www.python.org/dev/peps/pep-0398/#x-end-of-life

Signed-off-by: Rhys Kidd <rhyskidd@gmail.com>
Reviewed-by: Eric Engestrom <eric.engestrom@intel.com>