ix piglit-util.c compile error.
Remove the inclusion of GL/glew.h from piglit--util.c that was part
of commit fdc94ddf70629f5d7af7fd14245c366b4615c59b.

Fixes the following compiler error.
tests/util/piglit-util.c:31:21: error: GL/glew.h: No such file or directory

piglit-util.c doesn't reference anything from GLEW, so it's safe to
remove its inclusion.