utils: Move DRM_FORMATS defines to piglit_drm_dma_buf.h.
This patch fixes this build error.

transcode-nv12-as-r8-gr88.c: In function ‘create_textures’:
transcode-nv12-as-r8-gr88.c:178:7: error: ‘DRM_FORMAT_R8’ undeclared (first use in this function)
       DRM_FORMAT_R8, r8_pixels);
       ^

Fixes: 0222f5db00fd ("dmabuf: fix YUV tests for drivers other than intel")
Bugzilla: https://bugs.freedesktop.org/show_bug.cgi?id=97951
Signed-off-by: Vinson Lee <vlee@freedesktop.org>
Reviewed-by: Dylan Baker <dylan@pnwbakers.com>