glx_mesa_query_renderer: Fix error with GCC 10.
This patch fixes these build errors with GCC 10.

/usr/bin/ld: CMakeFiles/glx-query-renderer-coverage.dir/query-renderer-common.c.o:tests/spec/glx_mesa_query_renderer/query-renderer-common.h:49: multiple definition of `piglit_glXQueryRendererStringMESA'; CMakeFiles/glx-query-renderer-coverage.dir/coverage.c.o:tests/spec/glx_mesa_query_renderer/query-renderer-common.h:49: first defined here
/usr/bin/ld: CMakeFiles/glx-query-renderer-coverage.dir/query-renderer-common.c.o:tests/spec/glx_mesa_query_renderer/query-renderer-common.h:50: multiple definition of `piglit_glXQueryCurrentRendererStringMESA'; CMakeFiles/glx-query-renderer-coverage.dir/coverage.c.o:tests/spec/glx_mesa_query_renderer/query-renderer-common.h:50: first defined here
/usr/bin/ld: CMakeFiles/glx-query-renderer-coverage.dir/query-renderer-common.c.o:tests/spec/glx_mesa_query_renderer/query-renderer-common.h:51: multiple definition of `piglit_glXQueryRendererIntegerMESA'; CMakeFiles/glx-query-renderer-coverage.dir/coverage.c.o:tests/spec/glx_mesa_query_renderer/query-renderer-common.h:51: first defined here
/usr/bin/ld: CMakeFiles/glx-query-renderer-coverage.dir/query-renderer-common.c.o:tests/spec/glx_mesa_query_renderer/query-renderer-common.h:52: multiple definition of `piglit_glXQueryCurrentRendererIntegerMESA'; CMakeFiles/glx-query-renderer-coverage.dir/coverage.c.o:tests/spec/glx_mesa_query_renderer/query-renderer-common.h:52: first defined here
/usr/bin/ld: CMakeFiles/glx-query-renderer-coverage.dir/query-renderer-common.c.o:tests/spec/glx_mesa_query_renderer/query-renderer-common.h:53: multiple definition of `piglit_glXCreateContextAttribsARB'; CMakeFiles/glx-query-renderer-coverage.dir/coverage.c.o:tests/spec/glx_mesa_query_renderer/query-renderer-common.h:53: first defined here

Fixes: f6ed23b558ca ("query_renderer: Add some common infrastructure for GLX_MESA_query_renderer tests")
Signed-off-by: Vinson Lee <vlee@freedesktop.org>