fdo20701.c: Use __FUNCTION__ instead of __func__ with MSVC.
MSVC does not provide the C99 identifier __func__. Use the identifier
__FUNCTION__ instead when compiling with MSVC.

This fixes this MSVC fdo20701.c compiler error.
error C2065: '__func__' : undeclared identifier