intel_performance_query: Build only if EGL is available.
In file included from tests/spec/intel_performance_query/issue_2235.c:34:
tests/util/piglit-util-egl.h:28:10: fatal error: 'EGL/egl.h' file not found
         ^~~~~~~~~~~

Fixes: c85fad35569a ("tests: add test for assert in INTEL_performance_query")
Signed-off-by: Vinson Lee <vlee@freedesktop.org>
Reviewed-by: Lionel Landwerlin <lionel.g.landwerlin@intel.com>