cmake: Link utils with xcb explicitly
Linking CXX executables with gold linker leads to:
libpiglitutil_gl.so.0: error: undefined reference to 'xcb_connect'
libpiglitutil_gl.so.0: error: undefined reference to 'xcb_get_setup'
libpiglitutil_gl.so.0: error: undefined reference to 'xcb_setup_roots_iterator'

This may have appeared now because xcb-dri2 used to overlink publicly
but now does not.

Signed-off-by: Jussi Kukkonen <jussi.kukkonen@intel.com>
Reviewed-by: Emil Velikov <emil.velikov@collabora.com>