draw-prim-rate: Fix Clang build error.
draw-prim-rate.c:415:3: error: initializer element is not a compile-time constant
                ceil(sqrt(0.5 * 1000)),
                ^~~~~~~~~~~~~~~~~~~~~~

Fixes: 6e1bb1e769d2 ("Add a test that measures primitive rate")
Signed-off-by: Vinson Lee <vlee@freedesktop.org>
Reviewed-by: Marek Olšák <marek.olsak@amd.com>