util: Include time.h on all platforms.
Fix MinGW build error.

piglit-util.c: In function 'piglit_time_is_monotonic':
piglit-util.c:583:18: error: storage size of 't' isn't known
  struct timespec t;
                  ^

Fixes: e0048f4940f7 ("util: Add piglit_delay_ns() api")
Bugzilla: https://bugs.freedesktop.org/show_bug.cgi?id=98486
Signed-off-by: Vinson Lee <vlee@freedesktop.org>
Reviewed-by: Brian Paul <brianp@vmware.com>
Tested-by: Brian Paul <brianp@vmware.com>