glsl-1.30: update linker test for inter stage in/out vars usage
Adding additional in/out variable which exposes a new GLSL linker bug,
where we were using a variable in the IR which was later freed because
we forgot to clone it.

The test fails with the following error message:

    Failed to link:
    error: fragment shader input `bar' has no matching output
           in the previous stage

Signed-off-by: Vadym Shovkoplias <vadym.shovkoplias@globallogic.com>
Reviewed-by: Timothy Arceri <tarceri@itsqueeze.com>