arb_gpu_shader_fp64: Fix "undeclared identifier 'uint'" build error.
vs-non-uniform-control-flow-packing.c:91:2: error: use of undeclared identifier 'uint'; did you mean 'rint'?
        uint d0[2] = {0x0, 0x40000000};
        ^~~~
        rint
/usr/include/math.h:482:15: note: 'rint' declared here
extern double rint(double);
              ^

Fixes: c956a3ff3243 ("arb_gpu_shader_fp64: Add tests to check non-uniform-control-flow writes")
Signed-off-by: Vinson Lee <vlee@freedesktop.org>
Reviewed-by: Samuel Iglesias Gonsálvez <siglesias@igalia.com>