genclbuiltins: Add positional argument specifier.
Fix build failure with Python 2.6 introduced with commit
6adec8a68e2068114b9ff34ea462f22c32f80620.

Traceback (most recent call last):
  File "piglit/generated_tests/generate-cl-relational-builtins.py", line 194, in <module>
    main()
  File "piglit/generated_tests/generate-cl-relational-builtins.py", line 191, in main
    gen(DATA_TYPES, CLC_VERSION_MIN, functions, testDefs, dirName)
  File "piglit/generated_tests/genclbuiltins.py", line 395, in gen
    testIdx, vecSize, (fnType is 'tss'))
  File "piglit/generated_tests/genclbuiltins.py", line 333, in print_test
    f.write(' tolerance {} ulp'.format(tolerance))
ValueError: zero length field name in format

Signed-off-by: Vinson Lee <vlee@freedesktop.org>