khr_debug: Do not use dynamically sized arrays.
This patch fixes MSVC build errors introduced with commit
6a1250d27ee56afdddf532afe3edbc4e436355c7.

debug-object-label.c
debug-object-label.c(49) : error C2057: expected constant expression
debug-object-label.c(49) : error C2466: cannot allocate an array of constant size 0
debug-object-label.c(49) : error C2133: 'label' : unknown size
debug-object-label.c(112) : error C2057: expected constant expression
debug-object-label.c(112) : error C2466: cannot allocate an array of constant size 0
debug-object-label.c(112) : error C2133: 'length' : unknown size
debug-object-label.c(113) : error C2057: expected constant expression
debug-object-label.c(113) : error C2466: cannot allocate an array of constant size 0
debug-object-label.c(113) : error C2087: 'label' : missing subscript
debug-object-label.c(113) : error C2133: 'label' : unknown size
debug-object-label.c(282) : error C2057: expected constant expression
debug-object-label.c(282) : error C2466: cannot allocate an array of constant size 0
debug-object-label.c(282) : error C2133: 'label' : unknown size
debug-object-label.c(368) : error C2057: expected constant expression
debug-object-label.c(368) : error C2466: cannot allocate an array of constant size 0
debug-object-label.c(368) : error C2133: 'buffers' : unknown size
debug-object-label.c(370) : error C2057: expected constant expression
debug-object-label.c(370) : error C2466: cannot allocate an array of constant size 0
debug-object-label.c(370) : error C2133: 'label' : unknown size

Bugzilla: https://bugs.freedesktop.org/show_bug.cgi?id=70248
Signed-off-by: Vinson Lee <vlee@freedesktop.org>