arb_sample_shading: don't use gl_FragColor/Data in fragment shaders
NVIDIA's driver fails to compile the fragment shaders with "Failed to
compile fragment shader: 0(4) : error C7533: global variable gl_FragData
is deprecated after version 120".

Use 'out fragdata' or 'out fragcolor' instead.

Tested with Mesa too.

Reviewed-by: Neha Bhende <bhenden@vmware.com>