arb_texture_view: fix security format warnings
If built with -Werror=format-security then Piglit fails to build:

/tests/spec/arb_texture_view/rendering-layers-image.c:150:8:
error: format not a string literal and no format arguments [-Werror=format-security]
         (desc)); \
         ^~~~~~

In this case test->uniform_type is being turned into a string using snprintf()
and then passed to piglit_report_subtest_result() which takes a format string,
but GCC can't verify the format.

As _subtest_report() takes a format string, we can just remove the snprintf()
and let it construct the label.

Also as X is used once and doesn't make the code clearer, just inline it.

Signed-off-by: Ross Burton <ross.burton@intel.com>
Reviewed-by: Eric Engestrom <eric.engestrom@intel.com>