glx_arb_create_context: Fix build against older GL headers.
no-error.c: In function ‘check_no_error’:
no-error.c:37:3: error: ‘GLX_CONTEXT_OPENGL_NO_ERROR_ARB’ undeclared (first use in this function)
   GLX_CONTEXT_OPENGL_NO_ERROR_ARB, 1,
   ^

Fixes: 4991384f1332 ("glx: add test for GLX_ARB_create_context_no_error")
Signed-off-by: Vinson Lee <vlee@freedesktop.org>
Reviewed-by: Adam Jackson <ajax@redhat.com>