arb_internalformat_query2: Move global variable definitions to common.c.
This patch fixes these build errors with GCC 10.

/usr/bin/ld: CMakeFiles/arb_internalformat_query2-internalformat-size-checks.dir/common.c.o:tests/spec/arb_internalformat_query2/common.h:304: multiple definition of `valid_internalformats'; CMakeFiles/arb_internalformat_query2-internalformat-size-checks.dir/internalformat-size-checks.c.o:tests/spec/arb_internalformat_query2/common.h:304: first defined here
/usr/bin/ld: CMakeFiles/arb_internalformat_query2-internalformat-size-checks.dir/common.c.o:tests/spec/arb_internalformat_query2/common.h:305: multiple definition of `num_valid_internalformats'; CMakeFiles/arb_internalformat_query2-internalformat-size-checks.dir/internalformat-size-checks.c.o:tests/spec/arb_internalformat_query2/common.h:305: first defined here

Fixes: 1e60f1499e5b ("arb_internalformat_query2: test new ARB_ES3_compatibility internalformats")
Signed-off-by: Vinson Lee <vlee@freedesktop.org>
Reviewed-by: Jordan Justen <jordan.l.justen@intel.com>
Reviewed-by: Alejandro Piñeiro <apinheiro@igalia.com>
Tested-by: Marge Bot <https://gitlab.freedesktop.org/mesa/piglit/merge_requests/217>
Part-of: <https://gitlab.freedesktop.org/mesa/piglit/merge_requests/217>