arb_uniform_buffer: Fix block / field names in dlist test
Both the block name and the names of the individual variables in the
block live at global scope.  Therefore, they can't both have the same
names.  The GLSL 1.40 spec says:

    "Uniform block names and variable names declared within uniform
    blocks are scoped at the program level."

Previously this test failed on NVIDIA's closed-source driver (version
304.64) with the error messages:

0(2) : error C1002: the name "a" is already defined at 0(2)
0(3) : error C1002: the name "b" is already defined at 0(3)

With this change, the test passes.

Signed-off-by: Ian Romanick <ian.d.romanick@intel.com>
Reviewed-by: Eric Anholt <eric@anholt.net>